repos:
- repo: local
  hooks:
  - id: check-bad-keywords
    name: check for bad keywords
    entry: poetry run python ./dev-scripts/check-bad-keywords.py
    language: system
    stages: [pre-commit]
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0 # Use the ref you want to point at
  hooks:
    - id: trailing-whitespace
    - id: check-added-large-files
      args: [--maxkb=500]
    - id: check-case-conflict
    - id: check-merge-conflict
    - id: mixed-line-ending
      args: [--fix=auto]
    - id: fix-byte-order-marker
- repo: https://github.com/psf/black-pre-commit-mirror
  rev: 24.10.0
  hooks:
    - id: black
      language_version: python3.9
