close_of_business:
- go home!
- do some yoga!
- drink some water!
- Water your plants!
- Walk your dog!
- Pick up your kids!
- Go watch Netflix!
- Go nap!
- Go make some art!
- Go call a friend!
- Geddoutta'ere!
